DSONAME = SOP_TetEmbeddedDeform.so
INCDIRS = -I/usr/include/eigen3
SOURCES = TetMesh.cpp DeformationTracker.cpp SOP_TetEmbeddedDeform.cpp
OPTIMIZER = -O3

include $(HFS)/toolkit/makefiles/Makefile.gnu

